### ISSUE TITLE
how about for downloading file from url?

### ISSUE THREAD

**Issue by A-Programmer** [msmolka/ZNetCS.AspNetCore.ResumingFileResults#1]
Hello.
I want to download file from other urls for example my site is mysite.com and my files are on mysite2.com now I want to show link like mysite.come/file.zip but in fact file downloads from mysite2.com/file.zip without showing original file url to user.

**Comment by msmolka** [comment]
It is a bit tricky, but doable, however it is nothing to do with this package. All is supported out of box with .NET Core 2+

To do that you will need open connection to mysite2 on server side using HttpClient, pass all related resuming headers there and expose created stream to FileStreamResult.

**Comment by A-Programmer** [comment]
can you please give me an example? i searched many time but no result, tested many examples but no results. please give me an example.

**Comment by msmolka** [comment]
Sorry, this is not simple task, requires understanding how `HttpClient` works or `HttpWebRequest`, how to copy headers, which ones etc. I have no time to write such code.

**Comment by A-Programmer** [comment]
I searched and asked in ASP.NET Forum but they say it is not possible to do some thing like this

**Comment by msmolka** [comment]
It is possible, but by design it is wrong. The safest would be using low level `HttpWebRequest`, open connection copy related browser headers (quite a lot), get response headers, open response `Stream` and then pass that stream as a response of your action.

A lot of manual coding. A lot of problems to solve, like connection break, errors on your internal connection. Such solutions should be avoided.
